In [242]:
import numpy as np
import pandas as pd
import re

In [243]:
data = pd.read_csv("Data/Life_Expectancy_Data.csv")
pop_data = pd.read_csv("Data/population.csv")

In [244]:
max_pop = data['Population'].idxmax()

In [245]:
data.iloc[[max_pop]]

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
1187,India,2014,Developing,68.0,184.0,957,3.07,86.521539,79.0,79563,...,84.0,4.69,85.0,0.2,1573.11889,1.293859e+09,26.8,27.4,0.607,11.6

In [246]:
# Rows which have missing Values
# axis = 0: rows
# axis = 1: columns
# https://stackoverflow.com/questions/22149584/what-does-axis-in-pandas-mean
null_data = data[data.isnull().any(axis='columns')]

In [247]:
# 191 unique countries. Almost all countries have missing values.
#null_data

In [248]:
# Columns which have missing values
#data.isnull().sum()

In [249]:
# Number of cells which have missing values
#data.isnull().sum().sum()

In [250]:
# Column which has maximum NaN's. 
#data.isnull().sum().idxmax()

In [251]:
# Replace data in 'Population' column
# First find the minimum year in the dataset
# Computive Intensive. Comment for now.
#min_year = data['Year'].min()
#max_year = data['Year'].max()
#print("Range of Year:", min_year, "-", max_year)

In [252]:
# So we have to collect NaN data from 2000 - 2015 for 191 countries
#len(null_data['Country'].unique())

In [253]:
# What are the countries which have NaN Population?
nan_pop_countries = data[data['Population'].isnull()]
len(nan_pop_countries['Country'].unique())
# There are 49 countries which have some NaN population.

49

There are 49 countries which have some NaN population.

In [254]:
nan_countries_test = nan_pop_countries[['Country','Year', 'Population']]
#nan_countries_test['Population']
#nan_pop_countries['Country']
#nan_countries_test['Population'][2897]

In [255]:
#pop_data[pop_data['Country Name'] == "Antigua and Barbuda"][pop_data['Year'] == year[79]]['Value'].values[0]
#nan_pop_countries['Year'][64]
#pop_data[pop_data['Country Name'] == nan_pop_countries['Country'][64]][pop_data['Year'] == nan_pop_countries['Year'][64]]['Value'].values[0]
pop_data[pop_data['Country Name'] == nan_pop_countries['Country'][432]][pop_data['Year'] == nan_pop_countries['Year'][432]]
nan_pop_countries['Country'][432]

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.

"Côte d'Ivoire"

In [256]:
#pop_data[pop_data['Country Name'] == "Yemen"]
#pop_data.iloc[[160]]
len(pop_data[pop_data['Country Name'] == nan_pop_countries['Country'][850]].values)
#nan_pop_countries['Country'][850]
#pop_data[pop_data['Country Name'] == nan_pop_countries['Country'][850]]
#len(pop_data[pop_data['Country Name'] == nan_pop_countries['Country'][val]][pop_data['Year'] == nan_pop_countries['Year'][val]].values)
#pop_data['Country Name'].values[14716].split(',')[0]
#val = 432
#pop_data[pop_data['Country Name'].str.contains(nan_pop_countries['Country'][val])][pop_data['Year'] == nan_pop_countries['Year'][val]]['Value']

52

In [257]:
for val in nan_pop_countries['Country'].index:
    if np.isnan(nan_countries_test['Population'][val]):
        print(val,' ',end='')
        if len(pop_data[pop_data['Country Name'] == nan_pop_countries['Country'][val]].values) != 0:
            try:
                pop_other_data = pop_data[pop_data['Country Name'] == nan_pop_countries['Country'][val]][pop_data['Year'] == nan_pop_countries['Year'][val]]['Value'].values[0]
                print(pop_other_data)
                nan_countries_test.loc[val, 'Population'] = pop_other_data
            except IndexError:
                pass
        else:
            try:
                pop_other_data = pop_data[pop_data['Country Name'].str.startswith(nan_pop_countries['Country'][val])][pop_data['Year'] == nan_pop_countries['Year'][val]]['Value'].values[0]
                print(pop_other_data)
                nan_countries_test.loc[val, 'Population'] = pop_other_data
            except IndexError:
                try:
                    pop_other_data = pop_data[pop_data['Country Name'].str.startswith(nan_pop_countries['Country'][val].split(' (')[0])][pop_data['Year'] == nan_pop_countries['Year'][val]]['Value'].values[0]
                    print(pop_other_data)
                    nan_countries_test.loc[val, 'Population'] = pop_other_data
                except IndexError:
                    pass # No country match

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

64  99923.0
65  98875.0
66  97824.0
67  96777.0
68  95719.0
69  94661.0
70  93581.0
71  92478.0
72  91381.0
73  90301.0
74  89253.0
75  88257.0
76  87293.0
77  86266.0
78  85057.0
79  83584.0
160  386838.0
161  382169.0
162  377240.0
163  372039.0
164

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:13: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  del sys.path[0]

366568.0
165  360832.0
166  354856.0
167  348676.0
168  342328.0
169  335830.0
170  329249.0
171  322526.0
172  315746.0
173  309157.0
174  303135.0
175  297890.0
176  1371855.0
177  1336397.0
178  1315411.0
179  1300217.0
180  1278269.0
181  1240862.0
182  1185029.0
183  1114590.0
184  1035891.0
185  958414.0
186  889168.0
187  829848.0
188  778711.0
189  735148.0
190  697549.0
191  664614.0
208  284217.0
209  283385.0
210  282509.0
211  281585.0
212  280601.0
213  279569.0
214  278470.0
215  277319.0
216  276150.0
217  275039.0
218  274009.0
219  273091.0
220  272258.0
221  271478.0
222  270685.0
223  269847.0
304  10724705.0
305  10562159.0

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:18: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

306  10400264.0
307  10239004.0
308  10078343.0
309  9918242.0
310  9758748.0
311  9599855.0
312  9441444.0
313  9283334.0
314  9125409.0
315  8967741.0
316  8810420.0
317  8653345.0
318  8496375.0
319  8339512.0
368  417542.0
369  411704.0
370  405716.0
371  399748.0
372  394013.0
373  388662.0
374  383772.0
375  379252.0
376  374864.0
377  370250.0
378  365158.0
379  359523.0
380  353389.0
381  346867.0
382  340117.0
383  333241.0
432  433  434  435  436  437  438  439  440  441  442  443  444  445  446  447  608  76196619.0
609  73722860.0
610  71316033.0
611  68978682.0
612  66713597.0
613  64523263.0
614  62409435.0
615  60373608.0
616  58417562.0
617  56543011.0
618  54751476.0
619  53034217.0
620  51390033.0
621  49835756.0
622  48394338.0
623  47076387.0
624  657  11461432.0
658  11439767.0
659  11412167.0
660  11382146.0
661  11354651.0
662  11333051.0
663  11318602.0
664  11309754.0
665  11303687.0
666  11296233.0
667  11284253.0
668  11266941.0
669  11244885.0
670  11217998.0
671  11186542.0
672  11150736.0
689  690  691  692  693  694  695  696  697  698  699  700  701  702  703  704  705  706  707  708  709  710  711  712  713  714  715  716  717  718  719  720  721  722  723  724  725  726  727  728  729  730  731  732  733  734  735  736  769  72400.0
802  93778172.0
803  91812566.0
804  89807433.0
805  87813257.0
806  85897561.0
807  84107606.0
808  82465022.0
809  80953881.0
810  79537253.0
811  78159048.0
812  76778149.0
813  75381899.0
814  73981942.0
815  72590118.0
816  71226940.0
817  69905988.0
850  851  852  853  962  1977590.0
963  1917852.0
964  1859324.0
965  1802125.0
966  1746363.0
967  1692149.0
968  1639560.0
969  1588572.0
970  1539116.0
971  1491021.0
972  1444204.0
973  1398573.0
974  1354194.0
975  1311349.0
976  1270495.0
977  1231844.0
1042  106823.0
1043  106360.0
1044  105909.0
1045  105481.0
1046  105075.0
1047  104677.0
1048  104296.0
1049  103930.0
1050  103586.0
1051  103259.0
1052  102949.0
1053  102656.0
1054  102375.0
1055  102100.0
1056  101849.0
1057  101619.0
1218  79360487.0
1219  78411092.0
1220  77435384.0
1221  76453574.0
1222  75491582.0
1223  74567511.0
1224  73687565.0
1225  72845542.0
1226  72031103.0
1227  71227880.0
1228  70421811.0
1229  69617100.0
1230  68812713.0
1231  67983330.0
1232  67096414.0
1233  66131854.0
1394  3935794.0
1395  3782450.0
1396  3598385.0
1397  3395556.0
1398  3191051.0
1399  2998083.0
1400  2818939.0
1401  2652340.0
1402  2503410.0
1403  2377258.0
1404  2276623.0
1405  2207939.0
1406  2169118.0
1407  2143833.0
1408  2109355.0
1409  2050741.0
1410  1411  1412  1413  1414  1415  1416  1417  1418  1419  1420  1421  1422  1423  1424  1425  1426  1427  1428  1429  1430  1431  1432  1433  1434  1435  1436  1437  1438  1439  1440  1441  1506  6234955.0
1507  6204108.0
1508  6195970.0
1509  6198258.0
1510  6193501.0
1511  6169140.0
1512  6121053.0
1513  6053078.0
1514  5970362.0
1515  5881435.0
1516  5792688.0
1517  5704759.0
1518  5615952.0
1519  5527515.0
1520  5440566.0
1521  5355751.0
1650  52793.0
1699  104433.0
1700  104015.0
1701  103702.0
1702  103503.0
1703  103468.0
1704  103616.0
1705  103960.0
1706  104478.0
1707  105078.0
1708  105684.0
1709  106196.0
1710  106577.0
1711  106816.0
1712  106983.0
1713  107165.0
1714  107432.0
1715  37971.0
1812  10821.0
1845  4595700.0
1846  4509700.0
1847  4442100.0
1848  4408100.0
1849  4384000.0
1850  4350700.0
1851  4302600.0
1852  4259800.0
1853  4223800.0
1854  4184600.0
1855  4133900.0
1856  4087500.0
1857  4027200.0
1858  3948500.0
1859  3880500.0
1860  3857700.0
1909  1926  4199810.0
1927  3960925.0
1928  3711481.0
1929  3464644.0
1930  3237268.0
1931  3041460.0
1932  2882942.0
1933  2759014.0
1934  2662762.0
1935  2582991.0
1936  2511269.0
1937  2444751.0
1938  2385255.0
1939  2334285.0
1940  2294787.0
1941  2267991.0
2071  2481539.0
2072  2374419.0
2073  2250473.0
2074  2109568.0
2075  1952054.0
2076  1779676.0
2077  1590780.0
2078  1389342.0
2079  1189633.0
2080  1010382.0
2081  864863.0
2082  758855.0
2083  688586.0
2084  645659.0
2085  616886.0
2086  592267.0
2087  2088  2089  2090  2091  2092  2093  2094  2095  2096  2097  2098  2099  2100  2101  2102  2103  2104  2105  2106  2107  2108  2109  2110  2111  2112  2113  2114  2115  2116  2117  2118  2167  2168  2169  2170  2171  2172  2173  2174  2175  2176  2177  2178  2179  2180  2181  2182  2183  2184  2185  2186  2187  2188  2189  2190  2191  2192  2193  2194  2195  2196  2197  2198  2199  2216  32303.0
2233  31557144.0
2234  30776722.0
2235  29944476.0
2236  29086357.0
2237  28238020.0
2238  27425676.0
2239  26661492.0
2240  25940770.0
2241  25252569.0
2242  24578301.0
2243  23905654.0
2244  23228890.0
2245  22556425.0
2246  21906308.0
2247  21303592.0
2248  20764312.0
2313  5535002.0
2314  5469724.0
2315  5399162.0
2316  5312437.0
2317  5183688.0
2318  5076732.0
2319  4987573.0
2320  4839396.0
2321  4588599.0
2322  4401365.0
2323  4265762.0
2324  4166664.0
2325  4114826.0
2326  4175950.0
2327  4138012.0
2328  4027887.0
2329  2330  2331  2332  2333  2334  2335  2336  2337  2338  2339  2340  2341  2342  2343  2344  2377  13908129.0
2378  13513125.0
2379  13132349.0
2380  12763776.0
2381  12404725.0
2382  12053223.0
2383  11707990.0
2384  11369276.0
2385  11038596.0
2386  10718317.0
2387  10409925.0
2388  10116228.0
2389  9836397.0
2390  9564167.0
2391  9290823.0
2392  9011479.0
2585  2586  2587  2588  2589  2590  2591  2592  2593  2594  2595  2596  2597  2598  2599  2600  2746  9154302.0
2747  9070867.0
2748  9006263.0
2749  8900453.0
2750  8672475.0
2751  8270684.0
2752  7666393.0
2753  6894278.0
2754  6044067.0
2755  5242032.0
2756  4579562.0
2757  4087931.0
2758  3741932.0
2759  3507232.0
2760  3326032.0
2761  3154925.0
2762  2763  2764  2765  2766  2767  2768  2769  2770  2771  2772  2773  2774  2775  2776  2777  2778  2779  2780  2781  2782  2783  2784  2785  2786  2787  2788  2789  2790  2791  2792  2793  2794  2795  2796  2797  2798  2799  2800  2801  2802  2803  2804  2805  2806  2807  2808  2809  2858  31155134.0
2859  30738378.0
2860  30317848.0
2861  29893080.0
2862  29463291.0
2863  29028033.0
2864  28587323.0
2865  28141701.0
2866  27691965.0
2867  27239168.0
2868  26784161.0
2869  26327225.0
2870  25868523.0
2871  25408700.0
2872  24948476.0
2873  24488340.0
2874  2875  2876  2877  2878  2879  2880  2881  2882  2883  2884  2885  2886  2887  2888  2889  2890  26916207.0
2891  26246327.0
2892  25576322.0
2893  24909969.0
2894  24252206.0
2895  23606779.0
2896  22974929.0
2897  22356391.0
2898  21751605.0
2899  21160534.0
2900  20582927.0
2901  20017068.0
2902  19462086.0
2903  18919179.0
2904  18390135.0
2905  17874725.0

In [258]:
str1 = "GHJ"
str2 = "GHJ (jd)"
str1.startswith(str2.split(' (')[0])

True

In [259]:
nan_countries_test[['Country', 'Year', 'Population']]

                  Country  Year  Population
64    Antigua and Barbuda  2015     99923.0
65    Antigua and Barbuda  2014     98875.0
66    Antigua and Barbuda  2013     97824.0
67    Antigua and Barbuda  2012     96777.0
68    Antigua and Barbuda  2011     95719.0
69    Antigua and Barbuda  2010     94661.0
70    Antigua and Barbuda  2009     93581.0
71    Antigua and Barbuda  2008     92478.0
72    Antigua and Barbuda  2007     91381.0
73    Antigua and Barbuda  2006     90301.0
74    Antigua and Barbuda  2005     89253.0
75    Antigua and Barbuda  2004     88257.0
76    Antigua and Barbuda  2003     87293.0
77    Antigua and Barbuda  2002     86266.0
78    Antigua and Barbuda  2001     85057.0
79    Antigua and Barbuda  2000     83584.0
160               Bahamas  2015    386838.0
161               Bahamas  2014    382169.0
162               Bahamas  2013    377240.0
163               Bahamas  2012    372039.0
164               Bahamas  2011    366568.0
165               Bahamas  2010    360832.0
166               Bahamas  2009    354856.0
167               Bahamas  2008    348676.0
168               Bahamas  2007    342328.0
169               Bahamas  2006    335830.0
170               Bahamas  2005    329249.0
171               Bahamas  2004    322526.0
172               Bahamas  2003    315746.0
173               Bahamas  2002    309157.0
...                   ...   ...         ...
2876             Viet Nam  2013         NaN
2877             Viet Nam  2012         NaN
2878             Viet Nam  2011         NaN
2879             Viet Nam  2010         NaN
2880             Viet Nam  2009         NaN
2881             Viet Nam  2008         NaN
2882             Viet Nam  2007         NaN
2883             Viet Nam  2006         NaN
2884             Viet Nam  2005         NaN
2885             Viet Nam  2004         NaN
2886             Viet Nam  2003         NaN
2887             Viet Nam  2002         NaN
2888             Viet Nam  2001         NaN
2889             Viet Nam  2000         NaN
2890                Yemen  2015  26916207.0
2891                Yemen  2014  26246327.0
2892                Yemen  2013  25576322.0
2893                Yemen  2012  24909969.0
2894                Yemen  2011  24252206.0
2895                Yemen  2010  23606779.0
2896                Yemen  2009  22974929.0
2897                Yemen  2008  22356391.0
2898                Yemen  2007  21751605.0
2899                Yemen  2006  21160534.0
2900                Yemen  2005  20582927.0
2901                Yemen  2004  20017068.0
2902                Yemen  2003  19462086.0
2903                Yemen  2002  18919179.0
2904                Yemen  2001  18390135.0
2905                Yemen  2000  17874725.0

[652 rows x 3 columns]

In [267]:
nan_countries_test[nan_countries_test['Population'].isnull()].values

array([["Côte d'Ivoire", 2015, nan],
       ["Côte d'Ivoire", 2014, nan],
       ["Côte d'Ivoire", 2013, nan],
       ["Côte d'Ivoire", 2012, nan],
       ["Côte d'Ivoire", 2011, nan],
       ["Côte d'Ivoire", 2010, nan],
       ["Côte d'Ivoire", 2009, nan],
       ["Côte d'Ivoire", 2008, nan],
       ["Côte d'Ivoire", 2007, nan],
       ["Côte d'Ivoire", 2006, nan],
       ["Côte d'Ivoire", 2005, nan],
       ["Côte d'Ivoire", 2004, nan],
       ["Côte d'Ivoire", 2003, nan],
       ["Côte d'Ivoire", 2002, nan],
       ["Côte d'Ivoire", 2001, nan],
       ["Côte d'Ivoire", 2000, nan],
       ['Cook Islands', 2013, nan],
       ['Czechia', 2015, nan],
       ['Czechia', 2014, nan],
       ['Czechia', 2013, nan],
       ['Czechia', 2012, nan],
       ['Czechia', 2011, nan],
       ['Czechia', 2010, nan],
       ['Czechia', 2009, nan],
       ['Czechia', 2008, nan],
       ['Czechia', 2007, nan],
       ['Czechia', 2006, nan],
       ['Czechia', 2005, nan],
       ['Czechia', 2004, nan],
       ['Czechia', 2003, nan],
       ['Czechia', 2002, nan],
       ['Czechia', 2001, nan],
       ['Czechia', 2000, nan],
       ["Democratic People's Republic of Korea", 2015, nan],
       ["Democratic People's Republic of Korea", 2014, nan],
       ["Democratic People's Republic of Korea", 2013, nan],
       ["Democratic People's Republic of Korea", 2012, nan],
       ["Democratic People's Republic of Korea", 2011, nan],
       ["Democratic People's Republic of Korea", 2010, nan],
       ["Democratic People's Republic of Korea", 2009, nan],
       ["Democratic People's Republic of Korea", 2008, nan],
       ["Democratic People's Republic of Korea", 2007, nan],
       ["Democratic People's Republic of Korea", 2006, nan],
       ["Democratic People's Republic of Korea", 2005, nan],
       ["Democratic People's Republic of Korea", 2004, nan],
       ["Democratic People's Republic of Korea", 2003, nan],
       ["Democratic People's Republic of Korea", 2002, nan],
       ["Democratic People's Republic of Korea", 2001, nan],
       ["Democratic People's Republic of Korea", 2000, nan],
       ['Democratic Republic of the Congo', 2015, nan],
       ['Democratic Republic of the Congo', 2014, nan],
       ['Democratic Republic of the Congo', 2013, nan],
       ['Democratic Republic of the Congo', 2012, nan],
       ['Democratic Republic of the Congo', 2011, nan],
       ['Democratic Republic of the Congo', 2010, nan],
       ['Democratic Republic of the Congo', 2009, nan],
       ['Democratic Republic of the Congo', 2008, nan],
       ['Democratic Republic of the Congo', 2007, nan],
       ['Democratic Republic of the Congo', 2006, nan],
       ['Democratic Republic of the Congo', 2005, nan],
       ['Democratic Republic of the Congo', 2004, nan],
       ['Democratic Republic of the Congo', 2003, nan],
       ['Democratic Republic of the Congo', 2002, nan],
       ['Democratic Republic of the Congo', 2001, nan],
       ['Democratic Republic of the Congo', 2000, nan],
       ['Eritrea', 2015, nan],
       ['Eritrea', 2014, nan],
       ['Eritrea', 2013, nan],
       ['Eritrea', 2012, nan],
       ['Kyrgyzstan', 2015, nan],
       ['Kyrgyzstan', 2014, nan],
       ['Kyrgyzstan', 2013, nan],
       ['Kyrgyzstan', 2012, nan],
       ['Kyrgyzstan', 2011, nan],
       ['Kyrgyzstan', 2010, nan],
       ['Kyrgyzstan', 2009, nan],
       ['Kyrgyzstan', 2008, nan],
       ['Kyrgyzstan', 2007, nan],
       ['Kyrgyzstan', 2006, nan],
       ['Kyrgyzstan', 2005, nan],
       ['Kyrgyzstan', 2004, nan],
       ['Kyrgyzstan', 2003, nan],
       ['Kyrgyzstan', 2002, nan],
       ['Kyrgyzstan', 2001, nan],
       ['Kyrgyzstan', 2000, nan],
       ["Lao People's Democratic Republic", 2015, nan],
       ["Lao People's Democratic Republic", 2014, nan],
       ["Lao People's Democratic Republic", 2013, nan],
       ["Lao People's Democratic Republic", 2012, nan],
       ["Lao People's Democratic Republic", 2011, nan],
       ["Lao People's Democratic Republic", 2010, nan],
       ["Lao People's Democratic Republic", 2009, nan],
       ["Lao People's Democratic Republic", 2008, nan],
       ["Lao People's Democratic Republic", 2007, nan],
       ["Lao People's Democratic Republic", 2006, nan],
       ["Lao People's Democratic Republic", 2005, nan],
       ["Lao People's Democratic Republic", 2004, nan],
       ["Lao People's Democratic Republic", 2003, nan],
       ["Lao People's Democratic Republic", 2002, nan],
       ["Lao People's Democratic Republic", 2001, nan],
       ["Lao People's Democratic Republic", 2000, nan],
       ['Niue', 2013, nan],
       ['Republic of Korea', 2015, nan],
       ['Republic of Korea', 2014, nan],
       ['Republic of Korea', 2013, nan],
       ['Republic of Korea', 2012, nan],
       ['Republic of Korea', 2011, nan],
       ['Republic of Korea', 2010, nan],
       ['Republic of Korea', 2009, nan],
       ['Republic of Korea', 2008, nan],
       ['Republic of Korea', 2007, nan],
       ['Republic of Korea', 2006, nan],
       ['Republic of Korea', 2005, nan],
       ['Republic of Korea', 2004, nan],
       ['Republic of Korea', 2003, nan],
       ['Republic of Korea', 2002, nan],
       ['Republic of Korea', 2001, nan],
       ['Republic of Korea', 2000, nan],
       ['Republic of Moldova', 2015, nan],
       ['Republic of Moldova', 2014, nan],
       ['Republic of Moldova', 2013, nan],
       ['Republic of Moldova', 2012, nan],
       ['Republic of Moldova', 2011, nan],
       ['Republic of Moldova', 2010, nan],
       ['Republic of Moldova', 2009, nan],
       ['Republic of Moldova', 2008, nan],
       ['Republic of Moldova', 2007, nan],
       ['Republic of Moldova', 2006, nan],
       ['Republic of Moldova', 2005, nan],
       ['Republic of Moldova', 2004, nan],
       ['Republic of Moldova', 2003, nan],
       ['Republic of Moldova', 2002, nan],
       ['Republic of Moldova', 2001, nan],
       ['Republic of Moldova', 2000, nan],
       ['Saint Kitts and Nevis', 2013, nan],
       ['Saint Lucia', 2015, nan],
       ['Saint Lucia', 2014, nan],
       ['Saint Lucia', 2013, nan],
       ['Saint Lucia', 2012, nan],
       ['Saint Lucia', 2011, nan],
       ['Saint Lucia', 2010, nan],
       ['Saint Lucia', 2009, nan],
       ['Saint Lucia', 2008, nan],
       ['Saint Lucia', 2007, nan],
       ['Saint Lucia', 2006, nan],
       ['Saint Lucia', 2005, nan],
       ['Saint Lucia', 2004, nan],
       ['Saint Lucia', 2003, nan],
       ['Saint Lucia', 2002, nan],
       ['Saint Lucia', 2001, nan],
       ['Saint Lucia', 2000, nan],
       ['Saint Vincent and the Grenadines', 2015, nan],
       ['Saint Vincent and the Grenadines', 2014, nan],
       ['Saint Vincent and the Grenadines', 2013, nan],
       ['Saint Vincent and the Grenadines', 2012, nan],
       ['Saint Vincent and the Grenadines', 2011, nan],
       ['Saint Vincent and the Grenadines', 2010, nan],
       ['Saint Vincent and the Grenadines', 2009, nan],
       ['Saint Vincent and the Grenadines', 2008, nan],
       ['Saint Vincent and the Grenadines', 2007, nan],
       ['Saint Vincent and the Grenadines', 2006, nan],
       ['Saint Vincent and the Grenadines', 2005, nan],
       ['Saint Vincent and the Grenadines', 2004, nan],
       ['Saint Vincent and the Grenadines', 2003, nan],
       ['Saint Vincent and the Grenadines', 2002, nan],
       ['Saint Vincent and the Grenadines', 2001, nan],
       ['Saint Vincent and the Grenadines', 2000, nan],
       ['Slovakia', 2015, nan],
       ['Slovakia', 2014, nan],
       ['Slovakia', 2013, nan],
       ['Slovakia', 2012, nan],
       ['Slovakia', 2011, nan],
       ['Slovakia', 2010, nan],
       ['Slovakia', 2009, nan],
       ['Slovakia', 2008, nan],
       ['Slovakia', 2007, nan],
       ['Slovakia', 2006, nan],
       ['Slovakia', 2005, nan],
       ['Slovakia', 2004, nan],
       ['Slovakia', 2003, nan],
       ['Slovakia', 2002, nan],
       ['Slovakia', 2001, nan],
       ['Slovakia', 2000, nan],
       ['The former Yugoslav republic of Macedonia', 2015, nan],
       ['The former Yugoslav republic of Macedonia', 2014, nan],
       ['The former Yugoslav republic of Macedonia', 2013, nan],
       ['The former Yugoslav republic of Macedonia', 2012, nan],
       ['The former Yugoslav republic of Macedonia', 2011, nan],
       ['The former Yugoslav republic of Macedonia', 2010, nan],
       ['The former Yugoslav republic of Macedonia', 2009, nan],
       ['The former Yugoslav republic of Macedonia', 2008, nan],
       ['The former Yugoslav republic of Macedonia', 2007, nan],
       ['The former Yugoslav republic of Macedonia', 2006, nan],
       ['The former Yugoslav republic of Macedonia', 2005, nan],
       ['The former Yugoslav republic of Macedonia', 2004, nan],
       ['The former Yugoslav republic of Macedonia', 2003, nan],
       ['The former Yugoslav republic of Macedonia', 2002, nan],
       ['The former Yugoslav republic of Macedonia', 2001, nan],
       ['The former Yugoslav republic of Macedonia', 2000, nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2015,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2014,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2013,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2012,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2011,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2010,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2009,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2008,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2007,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2006,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2005,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2004,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2003,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2002,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2001,
        nan],
       ['United Kingdom of Great Britain and Northern Ireland', 2000,
        nan],
       ['United Republic of Tanzania', 2015, nan],
       ['United Republic of Tanzania', 2014, nan],
       ['United Republic of Tanzania', 2013, nan],
       ['United Republic of Tanzania', 2012, nan],
       ['United Republic of Tanzania', 2011, nan],
       ['United Republic of Tanzania', 2010, nan],
       ['United Republic of Tanzania', 2009, nan],
       ['United Republic of Tanzania', 2008, nan],
       ['United Republic of Tanzania', 2007, nan],
       ['United Republic of Tanzania', 2006, nan],
       ['United Republic of Tanzania', 2005, nan],
       ['United Republic of Tanzania', 2004, nan],
       ['United Republic of Tanzania', 2003, nan],
       ['United Republic of Tanzania', 2002, nan],
       ['United Republic of Tanzania', 2001, nan],
       ['United Republic of Tanzania', 2000, nan],
       ['United States of America', 2015, nan],
       ['United States of America', 2014, nan],
       ['United States of America', 2013, nan],
       ['United States of America', 2012, nan],
       ['United States of America', 2011, nan],
       ['United States of America', 2010, nan],
       ['United States of America', 2009, nan],
       ['United States of America', 2008, nan],
       ['United States of America', 2007, nan],
       ['United States of America', 2006, nan],
       ['United States of America', 2005, nan],
       ['United States of America', 2004, nan],
       ['United States of America', 2003, nan],
       ['United States of America', 2002, nan],
       ['United States of America', 2001, nan],
       ['United States of America', 2000, nan],
       ['Viet Nam', 2015, nan],
       ['Viet Nam', 2014, nan],
       ['Viet Nam', 2013, nan],
       ['Viet Nam', 2012, nan],
       ['Viet Nam', 2011, nan],
       ['Viet Nam', 2010, nan],
       ['Viet Nam', 2009, nan],
       ['Viet Nam', 2008, nan],
       ['Viet Nam', 2007, nan],
       ['Viet Nam', 2006, nan],
       ['Viet Nam', 2005, nan],
       ['Viet Nam', 2004, nan],
       ['Viet Nam', 2003, nan],
       ['Viet Nam', 2002, nan],
       ['Viet Nam', 2001, nan],
       ['Viet Nam', 2000, nan]], dtype=object)

In [268]:
nan_countries_test['Population'].isnull().sum()

263