In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_pickle("Data/New/Main_Data/Dataset.pkl")

In [4]:
data.head()

,Country,Year,Status,Life_Expectancy,Adult_Mortality,Infant_Deaths,Alcohol,Percentage_Expenditure,Measles,BMI_5-19_years,...,Under-Five_Deaths,Polio,Total_Expenditure,Diphtheria,GDP,Population,Thinness_10-19_years,Thinness_5-9_years,Income_Composition_Of_Resources,Schooling
0,Afghanistan,2014,Low income,63,234,64,0.03,9.7,492,17.2,...,86,58,12,62,625.34,32758020.0,17.7,17.7,0.441,3.5
1,Afghanistan,2013,Low income,62.7,235,66,0.03,8.8,430,17.1,...,89,62,10.59,64,647.966,31731688.0,17.9,18.0,0.443,3.5
2,Afghanistan,2012,Low income,62.2,242,69,0.04,7.9,2787,17.0,...,93,67,11.67,67,648.511,30696958.0,18.2,18.2,0.442,3.4
3,Afghanistan,2011,Low income,61.7,248,71,0.04,8.6,3013,16.9,...,97,68,10.17,68,599.298,29708599.0,18.4,18.4,0.426,3.3
4,Afghanistan,2010,Low income,61.2,255,74,0.03,8.6,1989,16.8,...,101,66,14.4,66,550.515,28803167.0,18.6,18.7,0.421,3.2