In [17]:
# Import modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import itertools

In [18]:
# Read in data
dat = pd.read_pickle("C:/Users/Sandeep/Documents/lifeexp_ml/Data/New/Main_Data/Final_Dataset.pkl")
dat.head()

,Country,Year,Status,Life_Expectancy,Adult_Mortality,Infant_Deaths,Alcohol,Percentage_Expenditure,Measles,BMI_5-19_years,...,Under-Five_Deaths,Polio,Total_Expenditure,Diphtheria,GDP,Population,Thinness_10-19_years,Thinness_5-9_years,Income_Composition_Of_Resources,Schooling
0,Afghanistan,2014,Low income,63.0,234,64.0,0.03,9.7,492.0,17.2,...,86.0,58,12.00,62,625.339539,32758020.0,17.7,17.7,0.441,3.5
1,Afghanistan,2013,Low income,62.7,235,66.0,0.03,8.8,430.0,17.1,...,89.0,62,10.59,64,647.966460,31731688.0,17.9,18.0,0.443,3.5
2,Afghanistan,2012,Low income,62.2,242,69.0,0.04,7.9,2787.0,17.0,...,93.0,67,11.67,67,648.511070,30696958.0,18.2,18.2,0.442,3.4
3,Afghanistan,2011,Low income,61.7,248,71.0,0.04,8.6,3013.0,16.9,...,97.0,68,10.17,68,599.297630,29708599.0,18.4,18.4,0.426,3.3
4,Afghanistan,2010,Low income,61.2,255,74.0,0.03,8.6,1989.0,16.8,...,101.0,66,14.40,66,550.514974,28803167.0,18.6,18.7,0.421,3.2

In [19]:
# Descriptive statistics
dat.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Year,2070.0,2.007000e+03,4.321538e+00,2000.000000,2.003000e+03,2.007000e+03,2.011000e+03,2.014000e+03
Life_Expectancy,2070.0,6.953174e+01,8.973576e+00,36.200000,6.330000e+01,7.180000e+01,7.590000e+01,8.380000e+01
Adult_Mortality,2070.0,1.875256e+02,1.080044e+02,50.000000,1.040000e+02,1.640000e+02,2.480000e+02,6.830000e+02
Infant_Deaths,2070.0,3.482012e+01,1.356658e+02,0.006617,9.020622e-01,3.000000e+00,2.300000e+01,1.837000e+03
Alcohol,2070.0,5.032581e+00,4.085902e+00,0.000000,1.302500e+00,4.325000e+00,8.207500e+00,1.775000e+01
Percentage_Expenditure,2070.0,6.183415e+00,2.490711e+00,1.000000,4.400000e+00,5.800000e+00,7.900000e+00,1.650000e+01
Measles,2070.0,2.647650e+03,1.173415e+04,0.000000,0.000000e+00,2.600000e+01,4.935000e+02,2.121830e+05
BMI_5-19_years,2070.0,1.889705e+01,1.325683e+00,15.600000,1.780000e+01,1.920000e+01,1.980000e+01,2.330000e+01
BMI_18+_years,2070.0,2.496734e+01,2.197830e+00,19.800000,2.300000e+01,2.550000e+01,2.660000e+01,3.180000e+01
Under-Five_Deaths,2070.0,4.800040e+01,1.848080e+02,0.006617,9.521156e-01,4.000000e+00,2.900000e+01,2.527000e+03
Polio,2070.0,8.660483e+01,1.444649e+01,24.000000,8.100000e+01,9.300000e+01,9.700000e+01,9.900000e+01
Total_Expenditure,2070.0,1.114781e+01,4.367337e+00,1.130000,7.862500e+00,1.080000e+01,1.414000e+01,2.917000e+01
Diphtheria,2070.0,8.645942e+01,1.515947e+01,19.000000,8.100000e+01,9.300000e+01,9.700000e+01,9.900000e+01
GDP,2070.0,1.169866e+04,1.784310e+04,111.363436,1.040139e+03,3.858227e+03,1.363983e+04,1.192254e+05
Population,2070.0,4.306072e+07,1.531250e+08,69670.000000,2.450885e+06,9.365664e+06,2.726469e+07,1.364270e+09
Thinness_10-19_years,2070.0,5.246039e+00,4.793498e+00,0.100000,1.600000e+00,3.600000e+00,7.900000e+00,2.780000e+01
Thinness_5-9_years,2070.0,5.217778e+00,4.864695e+00,0.100000,1.500000e+00,3.500000e+00,7.800000e+00,2.880000e+01
Income_Composition_Of_Resources,2070.0,6.678995e-01,1.829695e-01,0.181000,5.240000e-01,6.810000e-01,8.150000e-01,1.000000e+00
Schooling,2070.0,7.741020e+00,3.185769e+00,1.100000,5.200000e+00,7.900000e+00,1.050000e+01,1.400000e+01

In [20]:
dat.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2070 entries, 0 to 3239
Data columns (total 21 columns):
Country                            2070 non-null object
Year                               2070 non-null int64
Status                             2070 non-null object
Life_Expectancy                    2070 non-null float64
Adult_Mortality                    2070 non-null int64
Infant_Deaths                      2070 non-null float64
Alcohol                            2070 non-null float64
Percentage_Expenditure             2070 non-null float64
Measles                            2070 non-null float64
BMI_5-19_years                     2070 non-null float64
BMI_18+_years                      2070 non-null float64
Under-Five_Deaths                  2070 non-null float64
Polio                              2070 non-null int64
Total_Expenditure                  2070 non-null float64
Diphtheria                         2070 non-null int64
GDP                                2070 non-null float64
Population                         2070 non-null float64
Thinness_10-19_years               2070 non-null float64
Thinness_5-9_years                 2070 non-null float64
Income_Composition_Of_Resources    2070 non-null float64
Schooling                          2070 non-null float64
dtypes: float64(15), int64(4), object(2)
memory usage: 355.8+ KB

In [21]:
# One-hot encode the categorical column

X = pd.concat([dat,
               pd.get_dummies(dat['Country'],prefix='Country')],
              axis=1)
X = pd.concat([X,
               pd.get_dummies(dat['Year'],prefix='Year')],
              axis=1)
X = pd.concat([X,
               pd.get_dummies(dat['Status'],prefix='Status')],
              axis=1)

# Drop the original categorical column and the response variable
X = X.drop(['Status','Year','Country','Life_Expectancy'], axis=1)

X.sample(50)

,Adult_Mortality,Infant_Deaths,Alcohol,Percentage_Expenditure,Measles,BMI_5-19_years,BMI_18+_years,Under-Five_Deaths,Polio,Total_Expenditure,...,Year_2009,Year_2010,Year_2011,Year_2012,Year_2013,Year_2014,Status_High income,Status_Low income,Status_Lower middle income,Status_Upper middle income
2514,244,23.000000,0.33,4.6,0.000000,16.5,22.0,39.000000,84,12.41,...,0,0,0,0,0,0,0,1,0,0
2300,154,3.000000,6.64,6.2,0.000000,19.6,25.6,4.000000,82,10.19,...,1,0,0,0,0,0,0,0,0,1
2018,452,77.000000,0.60,6.2,183.000000,18.1,22.0,114.000000,73,15.19,...,0,0,0,0,0,0,0,1,0,0
1401,72,0.731616,12.42,9.1,57.000000,19.8,27.2,0.731616,93,15.56,...,0,0,0,0,0,0,1,0,0,0
632,140,11.000000,4.35,6.1,1.000000,19.1,25.8,13.000000,91,18.87,...,0,0,0,1,0,0,0,0,0,1
2921,338,15.000000,1.06,4.4,295.000000,17.7,22.2,23.000000,72,9.53,...,0,0,0,0,0,0,0,1,0,0
1113,263,38.000000,1.86,6.1,120.000000,17.5,23.5,56.000000,91,14.03,...,0,0,1,0,0,0,0,0,1,0
680,310,7.000000,3.50,2.2,1.000000,17.8,22.5,10.000000,76,4.62,...,1,0,0,0,0,0,0,0,1,0
821,323,2.000000,1.18,4.7,71.000000,18.3,23.4,2.000000,64,12.27,...,0,0,0,0,0,0,0,0,1,0
610,98,2.000000,6.98,6.9,0.000000,20.9,26.9,2.000000,94,12.67,...,0,0,0,0,0,0,1,0,0,0
517,376,56.000000,5.33,4.6,100.000000,18.1,23.5,88.000000,81,6.77,...,0,0,0,0,0,0,0,0,1,0
1363,187,181.000000,0.06,2.2,3825.000000,17.4,21.7,228.000000,77,4.54,...,0,0,0,0,0,0,0,0,1,0
26,107,1.000000,4.43,6.4,8.000000,19.5,25.4,1.000000,97,7.76,...,0,0,0,0,0,0,0,0,0,1
379,331,2.000000,5.61,5.6,853.000000,17.7,23.6,2.000000,96,8.62,...,0,1,0,0,0,0,0,0,0,1
1657,99,1.000000,1.72,8.6,373.000000,19.8,26.7,1.000000,75,10.45,...,0,0,0,0,0,0,0,0,0,1
2268,117,1.000000,7.05,6.0,4.000000,19.7,26.5,1.000000,91,12.85,...,0,0,1,0,0,0,1,0,0,0
1728,184,0.375456,14.88,6.5,7.000000,19.5,26.8,0.375456,92,12.25,...,0,0,1,0,0,0,1,0,0,0
653,262,2.000000,0.25,9.7,85.000000,17.7,23.3,2.000000,69,11.88,...,0,0,0,0,0,0,0,1,0,0
1096,73,2.000000,11.67,11.0,1771.000000,20.0,27.2,3.000000,94,19.25,...,0,0,0,0,1,0,1,0,0,0
205,187,0.434417,9.98,5.9,0.000000,20.9,27.0,0.434417,92,15.56,...,0,0,0,0,0,0,1,0,0,0
3151,159,9.000000,6.66,3.5,0.000000,20.3,26.6,11.000000,82,6.38,...,0,0,0,0,1,0,0,0,0,1
2131,153,2.000000,3.56,7.4,0.000000,20.1,26.6,2.000000,99,19.84,...,0,0,0,0,1,0,0,0,1,0
2790,184,0.074816,5.41,5.8,0.000000,19.9,26.4,0.074816,85,11.84,...,0,0,0,0,0,1,0,0,0,1
1050,235,2.000000,9.54,2.5,33.000000,18.5,24.8,3.000000,68,7.38,...,0,0,0,0,0,1,0,0,0,1
2232,130,1.000000,0.54,3.2,5.000000,19.3,25.3,1.000000,99,6.79,...,0,0,0,0,0,0,1,0,0,0
1082,157,1.000000,7.59,8.4,31.000000,19.4,27.4,1.000000,93,3.82,...,0,0,0,1,0,0,0,0,1,0
22,101,0.958209,5.76,6.1,22.000000,19.7,25.9,1.000000,99,8.88,...,0,0,0,0,0,0,0,0,0,1
2025,200,40.000000,1.78,4.9,122.000000,17.1,22.5,52.000000,88,3.59,...,0,0,0,0,0,1,0,0,1,0
1799,535,50.000000,1.38,4.4,304.000000,16.9,21.8,83.000000,73,8.98,...,0,0,0,0,0,0,0,1,0,0
1489,116,4.000000,0.52,8.1,0.000000,19.3,27.8,4.000000,98,19.46,...,0,1,0,0,0,0,0,0,0,1
1257,280,1.000000,7.85,4.8,0.000000,18.0,24.7,1.000000,93,11.29,...,0,0,0,0,0,0,0,0,0,1
669,392,8.000000,2.42,1.9,146.000000,17.7,22.2,12.000000,62,6.18,...,0,0,0,0,0,0,0,1,0,0
2898,161,2.000000,0.46,1.2,763.000000,17.0,20.7,3.000000,66,2.38,...,0,0,1,0,0,0,0,0,1,0
3032,335,71.000000,8.30,7.8,2027.000000,17.2,22.1,104.000000,79,14.34,...,0,0,0,1,0,0,0,1,0,0
2863,162,12.000000,0.94,4.3,38.000000,18.2,23.7,15.000000,84,6.41,...,0,0,0,0,0,0,0,1,0,0
2355,77,0.291696,10.35,9.0,8.307692,19.9,26.3,0.291696,98,11.91,...,0,0,0,0,0,1,1,0,0,0
250,116,0.387556,7.67,6.6,0.000000,20.0,26.9,0.387556,93,10.29,...,0,0,0,0,0,0,1,0,0,0
1829,142,0.353638,1.47,7.4,20.000000,17.3,22.6,0.353638,98,13.75,...,0,0,0,0,0,0,0,0,0,1
2497,102,7.000000,0.10,3.5,4648.000000,19.5,27.6,9.000000,96,7.94,...,0,0,0,0,0,0,1,0,0,0
2817,70,0.812318,6.90,8.4,9.000000,19.6,25.6,0.812318,99,13.52,...,0,0,0,0,0,0,1,0,0,0
2226,110,1.000000,0.54,2.0,18.000000,19.8,25.6,1.000000,97,5.41,...,0,0,0,0,0,0,1,0,0,0
3128,174,23.000000,1.93,5.6,823.000000,19.2,25.0,27.000000,94,11.81,...,0,0,0,0,0,0,0,0,1,0
2209,65,0.063233,6.59,8.9,3.000000,19.4,26.7,0.063233,93,17.42,...,0,1,0,0,0,0,1,0,0,0
2311,128,8.000000,5.06,4.8,0.000000,19.9,26.2,11.000000,71,14.38,...,0,0,0,0,1,0,0,0,0,1
641,155,16.000000,4.15,5.6,0.000000,18.6,24.9,19.000000,92,18.60,...,0,0,0,0,0,0,0,0,0,1
1146,75,0.715339,9.52,9.4,1.000000,20.8,27.5,0.715339,99,11.51,...,0,0,0,0,0,0,1,0,0,0
1051,251,2.000000,8.70,2.8,122.000000,18.5,24.7,3.000000,77,10.06,...,0,0,0,0,1,0,0,0,0,1
3145,168,0.226843,0.85,2.0,21.071429,18.5,25.4,0.226843,67,18.69,...,0,0,0,0,0,0,0,0,1,0
1882,219,8.000000,0.02,3.6,11.000000,17.9,24.0,12.000000,75,6.49,...,0,0,0,0,0,0,0,0,1,0
601,90,2.000000,7.23,7.4,0.000000,21.8,27.8,2.000000,90,15.32,...,0,0,0,0,1,0,1,0,0,0

In [22]:
y = dat['Life_Expectancy']
y.head()

0    63.0
1    62.7
2    62.2
3    61.7
4    61.2
Name: Life_Expectancy, dtype: float64

In [23]:
from sklearn.model_selection import train_test_split


# To make the result reproducible, set the random_state
train_y,test_y,train_X,test_X = train_test_split(y, X,
                                                 test_size=0.3,
                                                 
                                                 random_state=123)

In [24]:
#DECISION TREE
# import the regressor 
from sklearn.tree import DecisionTreeRegressor  
  
# create a regressor object 
regressor = DecisionTreeRegressor(random_state = 0)  
  
# fit the regressor with X and Y data 
regressor.fit(train_X, train_y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [26]:
# predicting a new value 
  
# test the output by changing values, like 3750 
y_pred = regressor.predict(test_X) 
  
# print the predicted price 
y_pred

array([78.8, 73.4, 56.5, 80.8, 72.8, 80.2, 68.4, 74.8, 73.2, 78.4, 71.1,
       73.7, 55. , 65.8, 80.9, 75.6, 78. , 62.5, 73.9, 68. , 66.3, 74.2,
       70.6, 56.1, 61. , 71.4, 68.8, 58.9, 80.6, 47.6, 81.9, 73.4, 53.5,
       82.2, 82.9, 75.2, 74.3, 77.2, 81. , 58.9, 71.3, 57.9, 82.2, 64.9,
       73. , 52.8, 61. , 80.3, 61.6, 76.3, 73. , 74.4, 70.2, 73.2, 72.1,
       57.5, 62.8, 53.1, 55. , 78. , 60.7, 51.4, 52.8, 73.4, 63.4, 74.9,
       80.6, 80.3, 68.6, 67.1, 72.6, 50.8, 80.7, 75.7, 82. , 78.8, 69.9,
       58. , 61.5, 74.3, 51.3, 66.1, 78.2, 55.3, 49.9, 72.4, 71.3, 81.1,
       59.9, 79. , 71.6, 64.7, 79.5, 53.7, 72. , 56.4, 73.7, 81.8, 75.9,
       80.9, 69. , 63.3, 73.8, 73.4, 67.8, 63.9, 73.7, 62.8, 72.3, 65.8,
       79.2, 73.6, 66.8, 51.4, 70.4, 75. , 57.9, 82.5, 46.4, 52.3, 69.9,
       82.9, 71.6, 79.5, 74.4, 61.9, 70.8, 63.1, 66.4, 49.5, 67.4, 56.6,
       80.3, 60.8, 79.2, 57.1, 48.9, 69.4, 65.8, 81.5, 69.2, 70.1, 72.2,
       71.1, 62.8, 76.2, 61.3, 59.6, 48.8, 57.2, 68.1, 72.7, 55.2, 75.4,
       73.6, 72.9, 64.4, 73. , 74.3, 82.1, 80.5, 77.5, 73.1, 82.3, 69.5,
       74.5, 78.5, 68.1, 75.5, 62.9, 82.1, 63.9, 50.8, 66.4, 80.2, 75.4,
       77. , 55.2, 72.3, 58. , 71.3, 76. , 78.1, 66.3, 80.3, 59.4, 82. ,
       49.4, 70.6, 72.1, 76.7, 67.2, 73.7, 72.2, 53.5, 79.2, 73.2, 48.5,
       69.9, 69.9, 76.2, 62.7, 64. , 81.5, 57.9, 75.5, 73.7, 81.1, 80.4,
       67.4, 81.8, 73.8, 76.3, 55.2, 69.4, 63.5, 60.8, 69.3, 48.6, 82.8,
       65.1, 56.3, 57.2, 76.6, 69.8, 66.7, 80.3, 54.9, 66.9, 60.8, 82.9,
       70.4, 75.4, 79.2, 59. , 81.2, 73.7, 56.3, 72.5, 69.5, 83. , 56.1,
       61.9, 82.8, 56.3, 80.7, 62.5, 59.2, 65. , 74.5, 57.1, 68.4, 78.1,
       49.5, 79. , 65.4, 67.5, 59.9, 76.5, 82.9, 55.4, 66. , 72.8, 67.9,
       56.6, 73.9, 69.2, 54.9, 74.5, 76.6, 72.7, 63.6, 70.5, 59. , 72.8,
       66.2, 55. , 63.1, 71.1, 51.4, 79.1, 67.1, 51.4, 65.6, 60.4, 74.1,
       78.8, 73.7, 66.1, 70.4, 66.4, 64.3, 80. , 72.8, 62.9, 79.5, 71.4,
       81. , 74.4, 65.1, 75.5, 56.3, 75.4, 78.3, 71.8, 78.9, 69.5, 76.6,
       77. , 56.3, 72.8, 52.8, 80.1, 80.6, 56.6, 53.1, 69.9, 72.2, 74.2,
       80.4, 62.3, 70.4, 78.8, 62.5, 62.1, 49.2, 72.4, 74.4, 70.5, 68.6,
       73. , 80.1, 74. , 69.1, 82.8, 53.5, 54.8, 57.4, 78.3, 71. , 46.2,
       70.4, 70.6, 70.4, 76.4, 72.4, 62.7, 69.1, 74.2, 56.1, 67.4, 74.2,
       56.2, 71.9, 80.9, 79.6, 76. , 79.1, 73.7, 54.3, 72.7, 63.5, 80. ,
       79. , 79.5, 77.1, 67.3, 58.4, 76.1, 79.3, 50.4, 70.8, 61.9, 79. ,
       50.4, 69.4, 62.7, 66.4, 77.5, 58.7, 78.7, 74.7, 70.4, 53.3, 72.5,
       76.2, 71.6, 60.2, 52.8, 52.5, 57.3, 60.2, 71.6, 72.3, 74.5, 74.9,
       68.9, 71.2, 63.4, 69.5, 79.2, 73. , 67.5, 67.4, 62.6, 51.5, 62.9,
       71.3, 78.3, 46.4, 52.3, 55. , 61. , 78. , 70.4, 61.6, 63. , 69.3,
       69.7, 73.3, 72.3, 64.7, 68.9, 70.9, 80.6, 80.8, 63.1, 70.6, 53.3,
       70.7, 80.9, 81.2, 75.2, 77.4, 74.5, 59.1, 79.9, 77.2, 71.1, 69.9,
       80.5, 65.1, 77.6, 74.9, 63.1, 76.2, 82.2, 79.5, 81. , 80.6, 68.8,
       75.9, 72.3, 74. , 74.9, 81.6, 70.7, 57.8, 81.8, 59.9, 59.9, 63. ,
       71. , 79.2, 80.4, 59.6, 70.4, 76.3, 71.9, 80. , 80.7, 70.6, 73.8,
       54.9, 71.5, 59.3, 73.7, 79.6, 69.8, 77.5, 60.8, 78.5, 71.4, 78.3,
       81.4, 73. , 63.2, 80.1, 73. , 71. , 80.5, 75.5, 78.1, 74.8, 74. ,
       45.9, 74.4, 73.2, 83. , 64.9, 75.5, 57.1, 71.2, 69.1, 58. , 72.7,
       50.8, 81.3, 77.7, 59.9, 74. , 76.1, 75.9, 72.5, 76.7, 73.6, 67.5,
       70.4, 70.5, 78.4, 72.9, 67.6, 77.7, 60.4, 73.5, 58.4, 75.1, 73.6,
       73.6, 67.5, 73.3, 80.5, 63.9, 71.6, 58.4, 60.4, 74.5, 79.2, 72.2,
       64.9, 73. , 58.6, 71.6, 75.2, 76.7, 69.4, 69.7, 75.5, 82.1, 77.3,
       80. , 74.5, 74.4, 53.2, 58.7, 82.2, 63.9, 75. , 80.5, 78.9, 77.6,
       72.3, 64.9, 63.7, 72.2, 58.3, 80.1, 67.8, 80.1, 72.3, 72.4, 82.2,
       70.7, 55.4, 71.6, 65.9, 47.1, 54. , 70.9, 74.1, 76.3, 69.5, 74.9,
       59.6, 51.4, 79.5, 75.4, 67.6, 68.3, 56.6, 81.9, 78.3, 62.8, 77. ,
       72.5, 54.5, 68.7, 44.4, 69.4, 74. , 53.5, 69.1, 74.4, 76.2, 80.3,
       58.6, 61.6, 72.7, 81.2, 67.8, 77.9, 71.8, 80.9, 78.8, 69.4, 66. ,
       60.4, 63.7, 70.6, 81.5, 74.9])

In [28]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(test_y, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(test_y, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(test_y, y_pred))) 
print('Explained variance score:', metrics.explained_variance_score(test_y, y_pred)) 
print('Median Absolute Error:', metrics.median_absolute_error(test_y, y_pred))

Mean Absolute Error: 0.7541062801932371
Mean Squared Error: 1.4745088566827707
Root Mean Squared Error: 1.2142935628103984
Explained variance score: 0.981672916485512
Median Absolute Error: 0.4000000000000057